### ISSUE TITLE
关于在toArray之前的field()操作

### ISSUE THREAD

**Issue by wxmatchmen** [easy-swoole/orm#112]
现在在toArray之前添加field()操作，toArrray会把$this->fields里的字段过滤掉之后输入，可否改变成只输出$this->fields里的字段,理由：
获取数据时，为了逻辑操作可能获取的数据比较多，在输出时只想输出某几个字段，这时候在toArray之前用field过滤掉不想要输出的字段，但是这样的操作没有field输出想要的字段代码清晰

**Comment by xuanyanwow** [comment]
你的应该是版本太旧，新版本field为筛选显示
