### ISSUE TITLE
ORM在invoke时，一对一关联和多对多关联，预查询都失效

### ISSUE THREAD

**Issue by dark-walk** [easy-swoole/orm#114]
`
$userData = UserModel::create()->get($this->userData['uid']);
$userDetails = $userData->relation;
        var_dump($userData);
        var_dump($userDetails);
`
用连贯操作是可以查询的，在invoke内再去取链接查询的时候，预查询与一对一关联均失效，返回null 没有执行hasone
`$userData = DbManager::getInstance()->invoke(function ($client){
         $userModel = UserModel::invoke($client);
         $userModel->get($this->userData['uid']);
         $userModel->relation();
         $userModel->with('relation');
         var_dump($userModel);
         $userDetails = $userModel->relation();
         var_dump($userDetails);
      });`

**Comment by xuanyanwow** [comment]
测试invoke中正常执行关联查询，详见单测：orm\tests\RelationToArrayTest.php   
 testGetInvokeRelation方法
