### ISSUE TITLE
多对多关联时，get()出现报错信息

### ISSUE THREAD

**Issue by kwdassk** [easy-swoole/orm#121]
表结构:
CREATE TABLE `tbl_user` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户昵称',
  `user_portrait` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户头像',
  `self_introduction` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '一句话介绍',
  `user_phone` varchar(11) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户手机号',
  `user_email` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户邮箱',
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '用户密码',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

CREATE TABLE `tbl_friend` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) unsigned NOT NULL COMMENT '用户id',
  `to_user_id` int(11) unsigned NOT NULL COMMENT '好友id',
  `group_id` int(11) unsigned NOT NULL COMMENT '分组id',
  `memo_name` varchar(255) DEFAULT NULL COMMENT '备注名',
  `status` tinyint(11) DEFAULT '4' COMMENT '状态 1.逻辑删除 2.已拒绝 3.已通过 4.未审核',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8 COMMENT='好友表';

UserModel:
        public function friend()
       {
            return $this->belongsToMany(UserModel::class, 'tbl_friend', 'to_user_id', 'user_id', function(QueryBuilder $builder){
            // 是目标表
           var_dump($builder);
           });
        }

Controller:
    function index()
    {
        $user = UserModel::create()->with(['friend'])->where(['id' => 3])->all();
        // 报错
        $user = UserModel::create()->with(['friend'])->get(3);
        $user = UserModel::create()->with(['friend'])->where(['id' => 3])->get();
        // $user->relUserRole();
        // $user->friend();
        $this->response()->write(json_encode($user));
    }

错误信息:
[2020-04-14 11:01:28][console][error]:[Argument 1 passed to App\Model\UserModel::App\Model\{closure}() must be an instance of EasySwoole\Mysqli\QueryBuilder, instance of App\Model\UserModel given at file:/var/www/html/new_kkk/App/Model/UserModel.php line:190]

附带问题：
多对多关联时想要获取到关联表里的数据

**Comment by xuanyanwow** [comment]
新版已修复
