### ISSUE TITLE
关于orm导致的内存耗尽

### ISSUE THREAD

**Issue by 729343861** [easy-swoole/orm#134]
报错信息：
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 262144 bytes) in /www/wwwroot/pro/vendor/easyswoole/orm/src/Concern/Attribute.php on line 45
[2020-05-14 02:37:41 $32570.0]	WARNING	swManager_check_exit_status: worker#31[pid=480] abnormal exit, status=255, signal=0

初步认为是因为使用了静态属性导致的。

![image](https://user-images.githubusercontent.com/35519825/81881792-a8b7ca80-95c3-11ea-8d37-1e8e3a4299c5.png)

**Comment by kiss291323003** [comment]
zheg
