### ISSUE TITLE
orm模型查询数据获取浮点类型失去精度问题

### ISSUE THREAD

**Issue by bodyTop** [easy-swoole/orm#138]
1.	在使用get 方法获取单行数据
 array(
     [xxx] => 0.0000001
)
通过数组key映射xxx 得到 value 为  1.0E-7
出现失精问题
具体细节文档发至vip群，如果的如果接受且采纳

**Comment by bodyTop** [comment]
这个bug确定有难度吗？咋不回信呢

**Comment by tioncico** [comment]
主要是大家都在忙哦,看到会回复的
