### ISSUE TITLE
关联以后不返回关联信息

### ISSUE THREAD

**Issue by livesitter** [easy-swoole/orm#149]
## 问题描述和截图 [Question]
我有两个表，Article表的ser_id关联User表
使用主键查询
![image](https://user-images.githubusercontent.com/27880065/85936563-a8cf1800-b92e-11ea-8289-e132bba250ef.png)
查询结果是这样的，并没有关联的信息
![image](https://user-images.githubusercontent.com/27880065/85936551-97860b80-b92e-11ea-99e2-b5efab10bd24.png)

然后我将user属性赋值给一个变量
![image](https://user-images.githubusercontent.com/27880065/85936573-c00e0580-b92e-11ea-836f-029ce714b0d8.png)
查询结果就成了这样
![image](https://user-images.githubusercontent.com/27880065/85936576-cbf9c780-b92e-11ea-8423-dc5585e9e366.png)

预期结果，使用主键查询的时候就返回带有关系信息的结果。

## 排查情况和最小复现脚本 [Tests and Recurrence]
链接: https://pan.baidu.com/s/1ZpFSIkZHBxCIwph9e0Y3uQ 提取码: 43bj

**Comment by xuanyanwow** [comment]
1.代码和结果为正常预期
2.自行思考：自动查询所有关联关系，在一对多、仅需要主记录几个字段的情况下，有效数据1单位，附带数据n倍单位。
3.自行看文档with预关联

**Comment by livesitter** [comment]
原来是查了这一步，谢谢哈
