### ISSUE TITLE
DbManager::getInstance()->isInTransaction($client); 返回的为false

### ISSUE THREAD

**Issue by beiqil-ban** [easy-swoole/orm#196]
## easyswoole框架版本号、orm组件版本号  [Version]
easyswoole: 3.4.1, orm: 1.4.40
## 问题描述和截图 [Question]
DbManager::getInstance()->isInTransaction($client); 返回的为false
<img width="573" alt="WechatIMG10057" src="https://user-images.githubusercontent.com/41405288/102321053-1a238580-3fb8-11eb-97e7-242672e903e0.png">
<img width="548" alt="WechatIMG10058" src="https://user-images.githubusercontent.com/41405288/102321058-1c85df80-3fb8-11eb-99b6-cee38109ab6e.png">

## 排查情况和最小复现脚本 [Tests and Recurrence]
 DbManager::getInstance()->invoke(function($client){
      $res = DbManager::getInstance()->startTransaction($client);
      var_dump($res);
      $res = DbManager::getInstance()->isInTransaction($client);
      var_dump($res);
      DbManager::getInstance()->rollback($client);
  });

**Comment by wxmatchmen** [comment]
ORM： 1.4.30

**Comment by XueSiLf** [comment]
在新的版本中已修复。请下载最新版本orm进行使用。
