### ISSUE TITLE
field方法有Bug

### ISSUE THREAD

**Issue by kyour-cn** [easy-swoole/orm#204]
## 问题描述和截图 [Question]
ExpressModel::create()
->field('id,status,explain')
->where(...)
->all();

执行报错，SQL：
explain FROM `express` WHERE `status` = ? AND `sid` = ?
去掉explain字段则不会出现

**Comment by liserven** [comment]
关键字？

**Comment by XueSiLf** [comment]
关键字了，用 反引号 处理下
