### ISSUE TITLE
处理查询条件时没有兼容主键可能是 string 类型的数字，可能导致清表

### ISSUE THREAD

**Issue by browningweb** [easy-swoole/orm#212]
https://github.com/easy-swoole/orm/blob/10157285f718caf1f27e3488b5aadaf5b2dc8e57/src/Utility/PreProcess.php#L19

`is_int($whereVal)` 判断能否改成 `is_numeric($whereVal)`，因为有时忘记类型转换，主键的值可能是 `string` 类型的，导致删除数据的时候没有条件，直接清表了。

**Comment by XueSiLf** [comment]
目前已经修复，#214，等待发布下1个版本
