### ISSUE TITLE
模型关联使用指定字段的BUG

### ISSUE THREAD

**Issue by uasunshine** [easy-swoole/orm#37]
<img width="630" alt="截屏2019-11-20上午11 04 36" src="https://user-images.githubusercontent.com/3658261/69205692-a5e49b80-0b85-11ea-8e82-0586846e3883.png"> 使用的时候这里进行了指定字段，

在进入AbstractModel 的 hasOne方法后（第764行和769行）调用的getOne方法会重置指定的字段为“*”

**Comment by xuanyanwow** [comment]
请提供orm版本号

若非最新版本  更新到最新版本重试

**Comment by uasunshine** [comment]
> 请提供orm版本号
> 
> 若非最新版本 更新到最新版本重试

ok 我本地用的是1.1 刚刚看了最新的版本。已经修改了这个问题。。3Q
