### ISSUE TITLE
联hasOne和hasMany希望增加支持 callable $field和callable order的支持

### ISSUE THREAD

**Issue by sqwindows** [easy-swoole/orm#38]
1.关联hasOne和hasMany能支持 callable $field和callable order就好了，这样可以设置关联表的指定字段和指定排序。不修改src源文件的情况下都不好覆盖这两个方法
2.field方法增加一个排除字段就好了，不然在不修改src源文件的情况只能覆盖feild方法 
3.希望可以增加trace记录跟踪执行语句

**Comment by xuanyanwow** [comment]
1.需要根据关联表复杂条件，可以传递第二个条件 where闭包，在其中注入QueryBuilder对象，可以调用所有连贯操作，比如field  order  where等
2.排除field字段会考虑 
3.可以设置onQuery回调，自己注入日志处理。 ES的设计是组件化，组件之间不强制关联，orm库只提供数据库操作部分，不提供日志部分，可以自己封装基类耦合日志组件做log
