### ISSUE TITLE
在task中orm查询构造器没有捕获异常

### ISSUE THREAD

**Issue by lxyzsl** [easy-swoole/orm#45]
查询exam_info_task表中的id字段正确使用下可以返回结果
![image](https://user-images.githubusercontent.com/17881085/69475735-970f1a80-0e0b-11ea-8a47-6674aa2228ca.png)
![image](https://user-images.githubusercontent.com/17881085/69475737-9e362880-0e0b-11ea-9df0-dd90bc6827b6.png)

但是如果我错误的把id写成了is则不会有异常抛出
![image](https://user-images.githubusercontent.com/17881085/69475739-aaba8100-0e0b-11ea-899a-c3119782028a.png)
![image](https://user-images.githubusercontent.com/17881085/69475742-b312bc00-0e0b-11ea-9c41-6f8b9f5248bc.png)

**Comment by xuanyanwow** [comment]
orm底层不会抛出异常，如swoole官方支持，查询失败会在结果对象设置errno error，需要先行判断是否存在失败情况。

参照文档  http://www.easyswoole.com/Components/Orm/lastResult.html

如果习惯抛出异常，可以自行封装基类Model  继承es官方Model   重写get all等方法，内部判断error  存在error则抛出异常
